[package]
name = "coffee_maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tokio = "1.21.2"
actix = "0.11.0"
actix-rt = "2.2"
util = {path="../common/util"}

